// import "./globals.css";
// import ClientLayout from "@/Components/ClientLayout";

// export const metadata = {
//   title: "VirtualDoc",
//   description: "Generated by create next app",
//   icons: {
//     icon: "/favicon.ico",
//   },
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <head>
//       </head>
//       <body>
//         <div >
//           <ClientLayout>{children}</ClientLayout>
//         </div>
//       </body>
//     </html>
//   );
// }


import { Geist, Geist_Mono } from "next/font/google";
import ClientLayout from "@/Components/ClientLayout";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "VirtualDoc",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div >
          <ClientLayout>{children}</ClientLayout>
        </div>
      </body>
    </html>
  );
}
